### ISSUE TITLE
Updated official release

### ISSUE THREAD

**Issue by pixsperdavid** [mas-bandwidth/yojimbo#152]
I created a Conan package (https://conan.io/center/yojimbo) for Yojimbo a while ago. As there's been quite a few new commits/merged PRs since the last official release (1.2.1), is it possible to get another official versioned release so I can update the package?

**Comment by risuwwv** [comment]
Hello, any update on this ? The current version in conan.io  has a few issues:
* https://github.com/conan-io/conan/issues/3573 says that `msvc` is planned to replace `Visual Studio` for `settings.compiler`
* Visual studio 2022 is not supported (but fixing the conanfile.py is not enough, [premake5 version in Conan](https://github.com/conan-io/conan-center-index/pull/10344) is stale too, I had to also replace it manually in my .conan/data folder locally)
* `yaml.load(...)` seems to be `yaml.full_load(...)` in recent versions.

Let me know if I should put the above in a separate issue.

**Comment by gafferongames** [comment]
Working on this now

**Comment by risuwwv** [comment]
Hello, the version on https://github.com/conan-io/conan-center-index/tree/master/recipes/yojimbo still seems to be 1.2.1 ?

**Comment by gafferongames** [comment]
Hi, I don't control Conan-io repo?

**Comment by gafferongames** [comment]
Hi, @pixsperdavid the current release should be appropriate for your Conan package. Do you have any time to update it?

**Comment by pixsperdavid** [comment]
I'll try and take a look at it at some point but pretty busy with other projects right now and I'm not using yojimbo in any code at present.
