### ISSUE TITLE
Yojimbo linkage 

### ISSUE THREAD

**Issue by McKillroy** [mas-bandwidth/yojimbo#181]
While working on the cmake/vcpkg port of yojimbo I stumbled over the fact that yojimbo is built as a static library only.
Is there a reason for that? Or could yojimbo be built as a .dll/.so as well? 
On Windows cmake could export all symbols by default like: 
```cmake 
SET(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS true)
```

**Comment by gafferongames** [comment]
It's a C++ library, generally when you export classes it gets messy due to name mangling and you'd need different dlls for gcc and visual c++, as they have different name mangling. It's best to leave it as static.
