### ISSUE TITLE
Improve vcpkg usage experience

### ISSUE THREAD

**Issue by bugproof** [mas-bandwidth/yojimbo#182]
You already have a port made but it's not findable here https://vcpkg.io/en/packages.html and it's harder to consume than all the other vcpkg libraries. Ideally it should reside in this repo https://github.com/microsoft/vcpkg/tree/master/ports so yojimbo would become available to install right after installing vcpkg. For example GameNetworkingSockets by Valve is easily findable there and much easier to consume than yojimbo.

![image](https://user-images.githubusercontent.com/3116731/186205092-118c0731-b122-45ab-8884-460bc45c559d.png)
![image](https://user-images.githubusercontent.com/3116731/186205166-7a420d54-2d7f-485c-a11a-6b6615fa1b33.png)

**Comment by gafferongames** [comment]
I have no idea how to do this, or time to do it, but I'd be happy to support anybody else doing this.

**Comment by bugproof** [comment]
I think the only way is [via PR to vcpkg repository](https://github.com/microsoft/vcpkg/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) and maintaining it there instead of the main yojimbo repo. The current way is fine but mostly used with closed source libraries and a bit longer to setup. I created an issue https://github.com/microsoft/vcpkg/issues/26485 maybe there is some other way that links to this repo.

**Comment by connorjustbecause** [comment]
This is huge! I use vcpkg for my projects, and I definitely agree, it's a lot harder to set up the current way. If you need any support, let me know!

**Comment by gafferongames** [comment]
If somebody wants to do this, please create a PR. I nuked the old vcpkg setup now that we don't depend on sodium and mbedtls so it should be much easier now. Thanks!
