### ISSUE TITLE
Large messages can clog ReliableOrderedChannel indefinitely

### ISSUE THREAD

**Issue by sherief** [mas-bandwidth/yojimbo#185]
This occurred on a configuration with `.maxPacketSize == 8192`. A message was generated, which serialized to `119500` bits. In `Connection::GeneratePacket()`, the `availableBits` is `65520`, and as that makes the call to `ReliableOrderedChannel::GetMessagesToSend()`, the condition at https://github.com/networkprotocol/yojimbo/blob/master/yojimbo.cpp#L1828 never fires since `entry->messageBits` is `119500` and so `availableBits >= (int) entry->measuredBits` always evaluates to false.

What do you think the behavior should be here? That packet is too large, but an early error would be much preferred to a quiet clog of the channel for the rest of the connection's lifetime.

**Comment by gafferongames** [comment]
I agree that an early out with an error (assert) is appropriate, since this is on send, and you should configure the channel size to be larger in this case. -- cheers

**Comment by dbechrd** [comment]
I just encountered this exact same problem and it took me quite awhile in the debugger looking through the yojimbo internals to figure out why my packet just silently disappeared on a reliable channel. This definitely needs an assert or some kind of obvious error. How can I even preventative check for this before calling SendMessage()? I don't see any obvious way in my Serialize() function to know when I've serialized too much to return false.

**Comment by dbechrd** [comment]
I was reading the code a bit more and just noticed this:
```cpp
#if YOJIMBO_DEBUG_MESSAGE_BUDGET
            if ( channelConfig.packetBudget > 0 )
            {
                yojimbo_assert( stream.GetBitsProcessed() - startBits <= channelConfig.packetBudget * 8 );
            }
#endif // #if YOJIMBO_DEBUG_MESSAGE_BUDGET
```

But it doesn't run in my case since packetBudget is -1 by default. I think @sherief 's commit would be nice to merge into the main repo, where they assert on availableBits, which comes from the Channel's maxPacketSize.
