### ISSUE TITLE
client.Disconnect() in loopback.cpp example

### ISSUE THREAD

**Issue by risuwwv** [mas-bandwidth/yojimbo#187]
Hello, looking at the documentation, I thought it should be client.DisconnectLoopback() in loopback.cpp ([here](https://github.com/networkprotocol/yojimbo/blob/97e93f00f92e74bcf2fcd7c64fd2ab891337deba/loopback.cpp#L139)), is that correct ?

**Comment by Green-Sky** [comment]
This issue tickled the back of my brain.... and yes, i found my old issue https://github.com/networkprotocol/yojimbo/issues/119

I think this is related, BUT it has been several years and i have not touched yojimbo in a while.

**Comment by gafferongames** [comment]
I think you are correct. Fixed.
