### ISSUE TITLE
Building.md instructions not working for m1 mac

### ISSUE THREAD

**Issue by matthewperiut** [mas-bandwidth/yojimbo#188]
I attempted to clone and compile Yojimbo, and it failed, but I'm not sure why. I would appreciate help figuring out my issue.
I have the pastebin of terminal logs here: https://pastebin.com/BEzmZraj
Although, important to note I am using an aarch64 M1 Pro. I'm not sure why make isn't recognizing mbedtls and libsodium, but any help is appreciated!

**Comment by Bowedyapper** [comment]
It is probably due to Homebrew keeping libraries and include files in `/opt/homebrew` as opposed to `usr/local` so it might be worth trying to use the environment variables clang look for to set an include and library path like so:

```sh
export LIBRARY_PATH=/opt/homebrew/lib && export C_INCLUDE_PATH=/opt/homebrew/include && make all
```

**Comment by matthewperiut** [comment]
> It is probably due to Homebrew keeping libraries and include files in `/opt/homebrew` as opposed to `usr/local` so it might be worth trying to use the environment variables clang look for to set an include and library path like so:
> 
> ```shell
> export LIBRARY_PATH=/opt/homebrew/lib && export C_INCLUDE_PATH=/opt/homebrew/include && make all
> ```

I attempted it and it still didn't work. I appreciate the sugguestion.

**Comment by gafferongames** [comment]
I'm working on this now, the dependencies on sodium and mbedtls have been removed.
