### ISSUE TITLE
matcher docker doesn't seem to build anymore

### ISSUE THREAD

**Issue by dbechrd** [mas-bandwidth/yojimbo#190]
Apparently the Go team deprecated the `go get` command. I don't know Go, and I tried googling for the last hour or so but couldn't figure out how to fix it. I tried updating the Dockerfile to contain various versions of `go install` and `go mod init` etc. but I don't really know what I'm doing. Perhaps you can figure it out?

![image](https://user-images.githubusercontent.com/707367/218372168-0fd164e2-3f3d-4be3-9232-b4f018e3df39.png)

yojimbo commit sha: `433bc2cee42bb372ad36d8b77a841dfd8f23c1f1`
```
$ premake5 --version
premake5 (Premake Build Script Generator) 5.0.0-beta2
```
```
$ go version
go version go1.20 windows/amd64
```
```
$ docker -v
Docker version 20.10.17, build 100c701
```

**Comment by gafferongames** [comment]
I'm working on this now. Sorry for the delay
