### ISSUE TITLE
Problem with #if in yojimbo_reliable_ordered_channel.cpp

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [mas-bandwidth/yojimbo#195]
When compiling with MSVC i get an error in yojimbo_reliable_ordered_channel.cpp(267,19): error C1017: invalid integer constant expression.
I think this is due to MSVC not support using `#if` to check for checking if `#define`s exists. So ifdef would have to be used instead or 
`YOJIMBO_DEBUG` would need to be assigned a value.

Compiler Version: Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33133 for x86
Targeting C++23

**Comment by gafferongames** [comment]
Awesome. Do you think you could create a small PR that fixes this issue?

**Comment by gafferongames** [comment]
OK I see the issue. I will make a small commit to fix this shortly. -- cheers

**Comment by gafferongames** [comment]
Fixed.
