### ISSUE TITLE
Minor issues found compiling with recent MSYS and MSVC

### ISSUE THREAD

**Issue by VA-GS** [mas-bandwidth/yojimbo#203]
Hello, I found the following small issues when building with
```
cat /proc/version
MSYS_NT-10.0-19045 version 3.5.3-d8b21b8c.x86_64 
```

inet_ntop and inet_pton in netcode.c are conflicting with ucrt64/include/ws2tcpip.h:
```
error: conflicting types for 'inet_ntop'; have 'const char *(int,  const void *, char *, socklen_t)' {aka 'const char *(int,  const void *, char *, int)'}
  184 |     const char *inet_ntop(int af, const void *src, char *dst, socklen_t cnt)
      |                 ^~~~~~~~~
In file included from Dependencies/yojimbo/netcode/netcode.c:148:
C:/msys64/ucrt64/include/ws2tcpip.h:400:35: note: previous declaration of 'inet_ntop' with type 'const CHAR *(INT,  const void *, CHAR *, size_t)' {aka 'const char *(int,  const void *, char *, long long unsigned int)'}
  400 | WINSOCK_API_LINKAGE LPCSTR WSAAPI InetNtopA(INT Family, LPCVOID pAddr, LPSTR pStringBuf, size_t StringBufSize);
      |                                   ^~~~~~~~~
```
Linking with `ws2_32` and removing the 2 definitions in netcode.c works. Not sure how to do this cleanly given that older MinGWs don't provide those.

There are 2 additional ";" [here](https://github.com/mas-bandwidth/netcode/blob/dcd03343426dd29c9363674adf15113e1cbc41b8/netcode.c#L3793) and [here](https://github.com/mas-bandwidth/netcode/blob/dcd03343426dd29c9363674adf15113e1cbc41b8/netcode.c#L2430).

With `Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33813 for x64`:
* I get an error with yojimbo_address.cpp and yojimbo_platform.cpp around NOMINMAX already being defined unless I add two `#ifndef NOMINMAX`.
* I compile without exceptions which causes some changes in the recursive include in MSVC headers, so I had to add `#include <malloc.h>` for alloca in
```
yojimbo_unreliable_unordered_channel.cpp
yojimbo_reliable_ordered_channel.cpp
yojimbo_channel.cpp
yojimbo_server.cpp
yojimbo_client.cpp
```

With the above, everything works great!

**Comment by gafferongames** [comment]
If you can create a PR, I'm happy to review it

**Comment by gafferongames** [comment]
And if you really want to lock it in, helping add a GitHub action to build under versions of MingW would make sure they keep working

**Comment by Green-Sky** [comment]
How did this issue come back, it was supposed to be fixed ages ago. https://github.com/mas-bandwidth/netcode/issues/89

I see that its behind this `#ifdef __MINGW32__` . I am not sure if all we need is to check the defined windows api version `#if _WIN32_WINNT >= _WIN32_WINNT_VISTA`

**Comment by gafferongames** [comment]
Somebody needs to add a test for building under MingW in Github actions, then it will stop breaking

**Comment by VA-GS** [comment]
I can do a PR for the changes I mentioned above if we agree on the #ifdef for inet_ntop. The Github action probably needs more work for MinGW.

**Comment by gafferongames** [comment]
As long as it compiles on existing platforms and passes tests. I'm happy. For GitHub actions, look at the .github directory. It's easy.
