### ISSUE TITLE
Why was MaxChannels reduced from 64 to 2?

### ISSUE THREAD

**Issue by dbechrd** [mas-bandwidth/yojimbo#204]
In this commit:
https://github.com/mas-bandwidth/yojimbo/commit/c006f7121047e5f1f660f2f8411c726411c35728

After updating my project to use the latest stable release of Yojimbo, it can not longer start the server, due to this assert:
![image](https://github.com/user-attachments/assets/2a044015-f3c1-4194-b9aa-1f1d5a7a0f9d)

**Comment by gafferongames** [comment]
Accidental change.

**Comment by dbechrd** [comment]
It's still set to 2 in the main branch and the latest stable release. Are you planning to revert the change? I've patched it locally for now, and haven't noticed any other issues with the stable release.

**Comment by gafferongames** [comment]
Stable release is going to get updated. Work around is to just increase it locally until the next release comes out
