### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by shelltitan** [mas-bandwidth/yojimbo#206]
https://github.com/mas-bandwidth/yojimbo/blob/b881662d72f21a171639fc6079052ce776cc9b2c/source/yojimbo_reliable_ordered_channel.cpp#L566C9-L566C21

`messageType = lockMessage->GetType();`

Seems to be a leftover from a bygone era? (I know it would be optimised out in code generation, so doesn't matter technically.)

**Comment by gafferongames** [comment]
Yes, I think in the past I had some mapping between message types that could have blocks, but then I was just like, woo everybody can have blocks. Feel free to open a PR with this line deleted. Thanks!
